### ISSUE TITLE
Jenkins Grails plugin does not list lastest versions of Grails

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-candidates#1]
@stigmelling commented on [Wed Apr 19 2017](https://github.com/sdkman/sdkman-cli/issues/563)

Looks like the Grails backend crawler (https://github.com/jenkinsci/backend-crawler/blob/master/grails.groovy) uses the list provided by http://api.sdkman.io/candidates/grails

The latest versions 3.2.8 and 2.5.6 are missing from the list. 

---

@marc0der commented on [Fri Apr 21 2017](https://github.com/sdkman/sdkman-cli/issues/563#issuecomment-296300369)

It turns out that this api endpoint was no longer being used by the cli client, so was subsequently orphaned. I wasn't aware that it was still being used by anyone. We have since done a lot of work to support multi platform candidates, which means that versions can vary between platforms (as they do for java). That said, Grails is a universal candidate that has consistent versions for all platforms.

I would need to implement a new endpoint specifically for this purpose that complies with out new API schema. I'll see what I can do to address this and report back here.

**Comment by marc0der** [comment]
@stigmellig I'e added a new endpoint that does exactly what you require. The cucumber specification describes exactly how it works. Let me know if this solves your problem. You might need to raise a further PR with the Jenkins Grails plugin to start using this endpoint.

The final endpoint will be: https://api.sdkman.io/2/candidates/versions/java/linux64/all. I'll post here when this is ready and deployed.

**Comment by marc0der** [comment]
Okay, that's been deployed and ready for action. Let me know how that goes!

**Comment by marc0der** [comment]
I've created a [pull request](https://github.com/jenkinsci/backend-crawler/pull/57) on the backend crawler for them to integrate with the new endpoint. Let's hope it gets merged quickly.

**Comment by stigmelling** [comment]
Great. Thanks :-)
