### ISSUE TITLE
Current versions of OpenJDK are no longer available

### ISSUE THREAD

**Issue by dchristofolli** [sdkman/sdkman-candidates#15]
The only available version of OpenJDK is 11.0.2, while the other JDKs are in version 11.0.9. Until last week, version 11.0.8 of OpenJDK was available.

**Comment by marc0der** [comment]
I don't think this is an issue with the candidates service. Please refer to the following issue for an explanation:
https://github.com/sdkman/sdkman-db-migrations/issues/374

In future, please consider asking a question on our Slack prior to opening an issue.
