### ISSUE TITLE
HTTP Secret key exposed in application.conf?

### ISSUE THREAD

**Issue by AndreasHae** [sdkman/sdkman-candidates#65]
I just noticed that there's a hard-coded secret key within the application config: https://github.com/sdkman/sdkman-candidates/blob/master/conf/application.conf#L2

I assume this gets overridden via environment variable on the production server? Otherwise this would be a security issue. If it gets overridden maybe add a comment for your fellow developers' peace of mind 😅

**Comment by marc0der** [comment]
Hey @AndreasHae, that key isn't used, but Play fails to start up if it isn't there. No secrets are being leaked, promise! 😄

**Comment by AndreasHae** [comment]
Hi @marc0der, thanks for clearing that up :) By the way, I wrote you a message on Slack about wanting to help out with the Rust-based sdkman client. Can you point me to any issues I could take over?
