### ISSUE TITLE
`mvnd` wants to default to `beta` version

### ISSUE THREAD

**Issue by Venorcis** [sdkman/sdkman-candidates#69]
I currently have `mvnd` version `1.0.1` installed, and `sdk upgrade` wants to push this to `2.0.0-beta-1`.

I wouldn't expect unstable versions to show up? Moreover their version 2 branch is based on Maven 4 (which is also still in beta), also mismatching the Maven candidate version (i.e. it is expectedly filtered out there).

**Comment by marc0der** [comment]
This candidate is published by the mvnd team via our vendors API, so it was probably done in error. I totally agree that we shouldn't be relying on unstable versions for default. Perhaps we could ask @cstamas to take a look for us.

**Comment by cstamas** [comment]
@gnodet pls take a look (he is publisher).

But yes, "stable" is 1.0.1, 2.0.0-beta-1 is more like "preview"

**Comment by marc0der** [comment]
I can set it back to 1.0.1 for now, but they should be aware not to do this again in the future.

**Comment by cstamas** [comment]
Script doing the work is here, maybe it needs to be modified on the master (where 2.0.0-betas are developed) to publish previews, but the one on mvnd-1.x branch (where 1.x is developed) is good as is?

https://github.com/apache/maven-mvnd/blob/master/build/publish-on-sdkman.sh

**Comment by marc0der** [comment]
Thanks @cstamas, I believe 1.x is correct. We're happy for you to keep publishing 2.x, just not setting it as candidate default until it reaches a stable state.

**Comment by Venorcis** [comment]
@cstamas @gnodet I know it's not sdkman-related, but I heard similar reports of the `brew` default being `2.0.0-beta-1` now, probably the same issue underpins it all 😄

**Comment by cstamas** [comment]
Brew introduced two formulas, mvnd and mvnd@1, i updated project readme. Brew is not quite for version mgmt like sdkman is, it always goes for the latest.

**Comment by marc0der** [comment]
I've updated our default to point at 1.0.1 again so this should solve your problem, @Venorcis. Feel free to close this issue if you like.

**Comment by Venorcis** [comment]
@marc0der thanks, can confirm it works as expected now indeed! thanks for the swift action 🚀
